name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Project
        run: |
          cd frontend
          npm run build

      - name: Upload to GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
